### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by mmontone**
Hi. These are the tests I've come up with.

I test at interface level (add, remove, replace advice; with and without arguments in functions).

Plugged the tests into ASDF. So you can run tests with `(asdf:test-system :cl-advice)`.

Please let me know of anything you would want changed.

Also, I've tested on SBCL, CCL and ECL. They all pass.

### CODE REVIEW

**Comment by mmontone** [comment]
Please consider squashing the commits if you decide to merge. The commit log is uninteresting.

**Comment by szos** [comment]
This looks great! One request, I know the example in the readme `:use`-s cl-advice, but would you mind not `:use`-ing cl-advice and instead keeping in the package qualifiers or explicitly import symbols? I prefer this as if tests are to be added/changed it makes it more difficult to use an internal symbol unintentionally. Looking through the tests it looks like the only place where a cl-advice symbol is used without a package qualifier is `defun-advisable`. 

Aside from that, this looks great! I may add some other tests for list-advice, remove-nth-advice, and advisable-lambda at a later date.

**Comment by mmontone** [comment]
Done

**Comment by szos** [comment]
Wonderful thanks! Ill squash and merge now.

**Comment by mmontone** [comment]
Great. Please ask to add to Quicklisp after :)

**Comment by szos** [comment]
Done, you can track the status here: https://github.com/quicklisp/quicklisp-projects/issues/2150

**Pull request merged**
